<?php

/**
 * @file
 * Primary module hooks for Dictionary import module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 *
 * Adds UniqueField constraint to Dictionary Entry field_word field.
 */
function dictionary_import_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() === 'node' && $bundle === 'dictionary_entry') {
    if (isset($fields['field_word'])) {
      $fields['field_word']->addConstraint('UniqueField', []);
    }
  }
}
